# Generated by Django 3.0.5 on 2021-05-22 11:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210522_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
