# Generated by Django 3.0.5 on 2021-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210517_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('banner', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='product', to='products.Product')),
            ],
        ),
    ]
