# Generated by Django 3.0.5 on 2021-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
